import '~/assets/css/components/markdown.css';

import React from 'react';
import Image from 'next/image';
import { getPost } from '~/server/data/getPost';
import { notFound } from 'next/navigation';

interface LayoutProps {
  children: React.JSX.Element;
  params: {
    id: string;
  };
}

export const runtime = 'edge';

export default async function Layout({ children, params }: LayoutProps) {
  const data = await getPost(params);

  if (!data) {
    notFound();
  }

  return (
    <>
      <div>
        <Image
          src={
            'https://www.notion.so/image/https%3A%2F%2Fdeno.com%2Fblog%2Froll-your-own-javascript-runtime-pt3%2Fcover.png?table=block&id=2c88c1a5-5539-4c3c-bd0b-1e09fc0e9170&spaceId=15edf32f-6b81-450f-acaf-9ce27666032a&width=1450&userId=cac42e24-7c10-4b08-9e06-37e8e30406b3&cache=v2'
          }
          placeholder="blur"
          // placeholder blur gray placeholder image generated by https://png-pixel.com/
          blurDataURL="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mN8/PFjPQAIygNGnW9D/wAAAABJRU5ErkJggg=="
          width={1450}
          height={800}
          className="mx-auto max-w-screen-sm w-full mt-4 sm:mt-0"
          alt={data?.title || 'preview'}
        />
      </div>
      {children}
    </>
  );
}
