import { type NextPage } from "next";
import Head from "next/head";
import SubNav from "~/components/shared/layouts/SubNav";
import Contents from "~/components/shared/layouts/Contents";
import Layout from "~/components/shared/layouts/Layout";
import PostList from "~/components/shared/common/PostList";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Contents subNav={<SubNav />} hasFlushed>
          <PostList />
        </Contents>
      </Layout>
    </>
  );
};

export default Home;
